In [2]:
img_path = '/home/alpaco/jeju/user/hdh/segmentation/dataset_jeju/result/20211128_1120/K3A_20200504045549_28203_00042683_L1R_br_visible.jpg'
img_path1 ='/home/alpaco/jeju/user/hdh/segmentation/dataset_jeju/result/20211128_1120/K3A_20201124045546_31286_00047175_L1R_br_visible.jpg'

In [9]:
import sys
import numpy as np
import cv2
from PIL import Image

In [4]:
a = Image.open(img_path1)
print(a.size)

(1112, 1024)


In [5]:

b = cv2.imread(img_path, cv2.IMREAD_COLOR)
b

array([[[ 47,  75,  45],
        [ 42,  73,  42],
        [ 43,  77,  47],
        ...,
        [ 49,  78,  45],
        [ 44,  73,  40],
        [ 44,  75,  42]],

       [[ 46,  74,  44],
        [ 42,  73,  42],
        [ 44,  75,  46],
        ...,
        [ 43,  72,  39],
        [ 45,  74,  41],
        [ 44,  75,  42]],

       [[ 46,  72,  42],
        [ 49,  77,  47],
        [ 46,  77,  46],
        ...,
        [ 47,  76,  43],
        [ 46,  75,  42],
        [ 46,  77,  44]],

       ...,

       [[ 45,  74,  41],
        [ 48,  77,  44],
        [ 42,  71,  38],
        ...,
        [  7, 233, 238],
        [  9, 232, 240],
        [  9, 232, 240]],

       [[ 46,  78,  43],
        [ 43,  75,  40],
        [ 43,  75,  40],
        ...,
        [ 11, 233, 238],
        [  5, 233, 240],
        [  3, 232, 241]],

       [[ 43,  76,  41],
        [ 42,  75,  40],
        [ 48,  80,  45],
        ...,
        [ 11, 233, 238],
        [  5, 232, 241],
        [  2, 233, 241]]

In [6]:
unique_colors = len(np.unique(b.reshape(-1, 3), axis=0))
print("이미지의 색상 종류 수:", unique_colors)

이미지의 색상 종류 수: 30314


In [58]:
tiff_path = '/home/alpaco/jeju/user/hdh/segmentation/dataset_jeju/result/20211128_1120/K3A_20200504045549_28203_00042683_L1R_br.tif'
tiff_path1 ='/home/alpaco/jeju/user/hdh/segmentation/dataset_jeju/result/20211128_1120/K3A_20201124045546_31286_00047175_L1R_br.tif'
tiff_path2='/home/alpaco/jeju/user/hdh/segmentation/dataset_jeju/result/20211128_1120/K3A_20210405050036_33281_00024452_L1R_br.tif'

In [66]:
a = Image.open(tiff_path2)
print(a.size)

(1156, 1024)


In [68]:

b = cv2.imread(tiff_path2, cv2.IMREAD_UNCHANGED)
b

array([[[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       [[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       [[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       ...,

       [[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       [[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]],

       [[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70],
        ...,
        [70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]]], dtype=uint8)

In [69]:
# array([[ 10,  10,  10], # 건물, 검정
#        [ 30,  30,  30], # 도로, 제일 진한 회색
#        [ 70,  70,  70], # 산림, 진한 회색
#        [ 90,  90,  90], # 농경지, 연한 회색
#        [100, 100, 100]], dtype=uint8) # 비대상지, 제일 연한 회색

In [70]:
import numpy as np

# 건물, 도로 --> 검은색
image_data = np.where(np.all(b == [30, 30, 30], axis=-1, keepdims=True), [10, 10, 10], b)
# 산림 --> 진한회색

# 비대상지, 농경지 --> 흰색
image_data = np.where(np.all(image_data == [100, 100, 100], axis=-1, keepdims=True), [255, 255, 255], image_data)
image_data = np.where(np.all(image_data == [90, 90, 90], axis=-1, keepdims=True), [255, 255, 255], image_data)
# 변경 후 이미지 확인
print("\n변경 후 이미지:\n", image_data)



변경 후 이미지:
 [[[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]

 [[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]

 [[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]

 ...

 [[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]

 [[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]

 [[70 70 70]
  [70 70 70]
  [70 70 70]
  ...
  [70 70 70]
  [70 70 70]
  [70 70 70]]]


In [71]:
unique_colors = len(np.unique(image_data.reshape(-1, 3), axis=0))
print("이미지의 색상 종류 수:", unique_colors)

이미지의 색상 종류 수: 3


In [72]:
unique_colors_list = np.unique(image_data.reshape(-1, 3), axis=0)
unique_colors_list

array([[ 10,  10,  10],
       [ 70,  70,  70],
       [255, 255, 255]])

In [73]:
cv2.imwrite("/home/alpaco/jeju/user/nsm/classchange.tif", np.array(image_data))

True

In [68]:
array([[ 10,  10,  10], # 건물, 검정
       [ 30,  30,  30], # 도로, 제일 진한 회색
       [ 70,  70,  70], # 산림, 진한 회색
       [ 90,  90,  90], # 농경지, 연한 회색
       [100, 100, 100]], dtype=uint8) # 비대상지, 제일 연한 회색

NameError: name 'array' is not defined